-- Active: 1762685719645@@localhost@5432@user_auth_db
### Register a new user
POST http://localhost:3000/api/register
Content-Type: application/json

{"email": "john@example.com","username": "johndoe","password": "securepass123","first_name": "John","last_name": "Doe"}

### 2. Login:
POST http://localhost:3000/api/login
Content-Type: application/json

{
   "username": "johndoe",
   "password": "securepass123"
  }

### 3. Get all users:
GET http://localhost:3000/api/users

### 4. Get user by ID:
GET http://localhost:3000/api/users/1

### 5. Update user:
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
   "first_name": "Jane",
   "last_name": "Smith"
  }