### Get all to-do items
GET http://localhost:3000/todos

### Create a new to-do item with a JSON request body
POST http://localhost:3000/todos
Content-Type: application/json

{
   "task":"Read Quran"
   }

### Update a to-do item by ID with a JSON request body
PUT http://localhost:3000/todos/1
Content-Type: application/json

{
   "completed": true
}

### Delete a to-do item by Id
DELETE http://localhost:3000/todos/2
